name: Commit build docker
name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        token: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        repository: interstellarkai/wallstreetai
        dockerfile: /Dockerfile
        tags: interstellarkai/wallstreetai:latest